/* =========================================================
   PHARMA 3D — Practice question bank
   Format: [level, domain, question, [options], answerIndex, explanation]
   Levels: Beginner, Intermediate, Advanced, Research
   General textbook-level content for self-study. Not an official exam.
   ========================================================= */
window.P4_MCQ = (function () {
  var B = "Beginner", I = "Intermediate", A = "Advanced", R = "Research";
  var raw = [
    /* ---------- BEGINNER ---------- */
    [B, "Pharmaceutics", "Which dosage form is designed to be placed under the tongue so the drug is absorbed through the oral mucosa?", ["Enteric-coated tablet", "Sublingual tablet", "Suppository", "Transdermal patch"], 1, "Sublingual tablets dissolve under the tongue, and drug absorbs through the mucosa directly into the venous drainage, avoiding first-pass metabolism in the liver."],
    [B, "Pharmacology", "What does ‘bioavailability’ describe?", ["The shelf life of a drug", "The fraction of a dose reaching the systemic circulation unchanged", "The colour of a formulation", "The rate of tablet disintegration only"], 1, "Bioavailability (F) is the fraction of the administered dose that reaches the systemic circulation. By definition it is 1 for an intravenous dose."],
    [B, "Pharmacology", "The ‘half-life’ of a drug during first-order elimination is the time taken for its plasma concentration to…", ["Double", "Fall by half", "Reach zero", "Reach Cmax"], 1, "During first-order elimination, concentration falls by half every half-life, t½ = 0.693 / k."],
    [B, "Pharmacovigilance", "An unwanted medical event in a patient taking a medicine, whether or not the medicine caused it, is called a…", ["Adverse event", "Placebo effect", "Drug interaction only", "Contraindication"], 0, "An adverse event is any untoward occurrence during treatment, whether or not a causal link exists. A reaction (ADR) implies at least a reasonable possibility of causation."],
    [B, "Pharmaceutics", "Which is the main purpose of an enteric coating on a tablet?", ["Make it taste sweeter", "Resist stomach acid and release in the intestine", "Speed up disintegration in the stomach", "Increase the tablet weight"], 1, "Enteric coatings resist the low pH of the stomach and dissolve at higher pH in the small intestine, protecting acid-labile drugs or the stomach lining."],
    [B, "Pharmacognosy", "Pharmacognosy is best described as the study of…", ["Drugs derived from natural sources", "Tablet compression", "Drug receptors only", "Hospital management"], 0, "Pharmacognosy studies medicinal drugs from plants, animals, minerals and microbes, including their identification and constituents."],
    [B, "Analysis", "In HPLC, the time from injection to the peak maximum of a compound is called its…", ["Retention time", "Half-life", "Dissolution time", "Lag time"], 0, "Retention time is the time a compound takes to elute from the column and is used, together with standards, to help identify it."],
    [B, "Pharmaceutics", "Which excipient function best fits a ‘disintegrant’ in a tablet?", ["Helps the tablet break apart in fluid", "Adds colour", "Prevents oxidation", "Reduces sticking to the die only"], 0, "Disintegrants promote breakup of the tablet into smaller particles after contact with fluid, helping dissolution."],
    [B, "Microbiology", "Which term describes a substance that kills or inhibits growth of microorganisms on living tissue?", ["Antiseptic", "Sterilant", "Excipient", "Adjuvant"], 0, "Antiseptics are used on living tissue; disinfectants are for inanimate surfaces; sterilisation removes all viable microorganisms."],
    [B, "Pharmacology", "An agonist is a substance that…", ["Blocks a receptor without activating it", "Binds a receptor and activates it", "Destroys the receptor", "Only binds enzymes"], 1, "An agonist binds and activates a receptor to produce a response. An antagonist binds but does not activate, and blocks agonist action."],
    [B, "Biostatistics", "The mean of the numbers 2, 4, 6 and 8 is…", ["4", "5", "6", "20"], 1, "Mean = (2+4+6+8)/4 = 5."],
    [B, "Pharmaceutics", "A ‘suspension’ is best described as…", ["A solution with no particles", "Fine insoluble solid particles dispersed in a liquid", "Two mixed liquids only", "A solid dosage form"], 1, "In a suspension, insoluble drug particles are dispersed in a liquid vehicle, and usually need shaking before use."],
    [B, "Pharmacology", "Which route of administration avoids first-pass hepatic metabolism most completely?", ["Oral", "Intravenous", "Rectal only", "All routes equally"], 1, "Intravenous administration delivers the drug straight into the systemic circulation. Oral drugs pass through the liver first via the portal vein."],
    [B, "Pharmacovigilance", "Spontaneous reporting of suspected adverse reactions is mainly used to…", ["Detect possible safety signals after a medicine is marketed", "Prove a drug is completely safe", "Set the price of a medicine", "Replace clinical trials"], 0, "Spontaneous reporting supports post-marketing surveillance and can generate signals, though it cannot measure incidence."],
    [B, "Analysis", "In UV–visible spectrophotometry, Beer–Lambert law relates absorbance to…", ["Concentration and path length", "Melting point", "Particle size", "Viscosity"], 0, "A = ε·c·l: absorbance is proportional to concentration and path length for a given absorbing species and wavelength."],
    [B, "Pharmaceutics", "Which is the usual purpose of a lubricant such as magnesium stearate in a tablet formulation?", ["Reduce friction between tablet and die during compression", "Sweeten the tablet", "Protect from light", "Increase disintegration in all cases"], 0, "Lubricants reduce friction during ejection from the die. Excess can slow dissolution by making the tablet more hydrophobic."],

    /* ---------- INTERMEDIATE ---------- */
    [I, "Pharmacokinetics", "In a one-compartment model after an IV bolus, clearance (CL) equals…", ["k × Vd", "Vd / k", "Dose × k", "C0 / Dose"], 0, "CL = k·Vd, where k is the elimination rate constant and Vd the volume of distribution."],
    [I, "Pharmacokinetics", "For an IV bolus in a one-compartment model, AUC(0–∞) is given by…", ["Dose / CL", "Dose × CL", "CL / Vd", "Dose / Vd"], 0, "AUC(0–∞) = Dose / CL for an IV dose (F = 1). For oral doses, AUC = F·Dose / CL."],
    [I, "Pharmacokinetics", "In the Bateman function, increasing the absorption rate constant ka (with k fixed) generally…", ["Lowers Cmax and delays Tmax", "Raises Cmax and shortens Tmax", "Changes AUC in proportion to ka", "Has no effect on the curve"], 1, "Faster absorption gives a higher, earlier peak. AUC(0–∞) = F·Dose/CL does not depend on ka."],
    [I, "Pharmaceutics", "Which mechanism best describes drug release from an inert, non-swelling matrix, as modelled by the Higuchi equation?", ["Diffusion, with cumulative release proportional to √t", "Zero-order release", "Erosion only", "Osmotic pumping"], 0, "The Higuchi model, under its assumptions, gives cumulative release proportional to the square root of time."],
    [I, "Pharmaceutics", "The Korsmeyer–Peppas equation is Mt/M∞ = k·tⁿ. What does the exponent n help describe?", ["The release pattern (for example diffusion-like versus relaxation-like)", "The drug’s melting point", "The particle charge", "The tablet hardness"], 0, "n is used as an indicator of release behaviour, with geometry-specific cut-offs, but a fit alone does not prove mechanism."],
    [I, "Pharmaceutics", "Zeta potential of a colloidal dispersion is mainly used as an indicator of…", ["Surface charge and electrostatic stability", "Drug potency", "Melting behaviour", "Tablet friability"], 0, "Zeta potential reflects surface charge and can indicate electrostatic repulsion between particles, but depends on pH and ionic strength."],
    [I, "Pharmaceutics", "Polydispersity index (PDI) from dynamic light scattering describes…", ["Breadth of the size distribution", "Drug content", "Zeta potential", "Crystal form"], 0, "PDI is a dimensionless measure of how broad the particle-size distribution is."],
    [I, "Pharmacology", "A drug with a large volume of distribution (Vd) generally…", ["Distributes extensively into tissues beyond plasma", "Stays mostly in plasma", "Has no clearance", "Is always highly protein bound in plasma"], 0, "A large apparent Vd indicates extensive distribution into tissues relative to plasma; it is not a real anatomical volume."],
    [I, "Pharmacovigilance", "In the 2×2 table used for disproportionality analysis, ‘a’ represents reports of…", ["The drug of interest with the event of interest", "Other drugs with the event", "The drug with other events", "Other drugs with other events"], 0, "a = drug of interest and event of interest; b = drug and other events; c = other drugs and the event; d = other drugs and other events."],
    [I, "Pharmacovigilance", "The Proportional Reporting Ratio (PRR) is calculated as…", ["[a/(a+b)] / [c/(c+d)]", "(a+b) / (c+d)", "a × d", "a / N"], 0, "PRR compares the proportion of a drug’s reports naming the event with that proportion for all other drugs."],
    [I, "Pharmacovigilance", "A Naranjo score in the range 5–8 is categorised as…", ["Probable", "Definite", "Possible", "Doubtful"], 0, "Naranjo categories: ≥9 definite, 5–8 probable, 1–4 possible, ≤0 doubtful."],
    [I, "Analysis", "In HPLC, which change would generally shorten the retention time of a non-polar analyte on a reversed-phase C18 column?", ["Increase the proportion of organic solvent in the mobile phase", "Decrease the organic solvent proportion", "Lower the flow rate", "Use a longer column"], 0, "In reversed-phase chromatography a stronger (more organic) mobile phase elutes non-polar analytes sooner."],
    [I, "Pharmaceutics", "Which best describes ‘ionic gelation’ in the context of chitosan nanoparticles?", ["Electrostatic crosslinking of a polycation with a polyanion", "Covalent crosslinking with a solvent", "Melting and cooling of a polymer", "Freeze-drying a suspension"], 0, "Ionic gelation uses electrostatic interaction between positively charged chitosan and a polyanion such as tripolyphosphate."],
    [I, "Pharmaceutics", "Encapsulation efficiency (EE%) by the indirect method is calculated from…", ["(Total drug − free drug) / total drug × 100", "Free drug / total drug × 100", "Total drug × free drug", "Nanoparticle mass / total drug"], 0, "EE% = (Initial drug − free/unencapsulated drug) / Initial drug × 100."],
    [I, "Biostatistics", "A p-value of 0.03 in a hypothesis test most directly means…", ["If the null hypothesis were true, data this extreme would occur about 3% of the time", "There is a 97% chance the drug works", "The effect is large", "The null hypothesis is 3% likely"], 0, "The p-value is the probability of observing data at least this extreme if the null hypothesis were true. It is not the probability that a hypothesis is true."],
    [I, "Regulatory", "Good Manufacturing Practice (GMP) is primarily concerned with…", ["Ensuring products are consistently produced and controlled to quality standards", "Setting drug prices", "Advertising rules", "Prescribing rules"], 0, "GMP provides a framework of practices ensuring medicines are consistently produced and controlled according to quality standards."],
    [I, "Microbiology", "Which is a key difference between bacteriostatic and bactericidal antibiotics?", ["Bacteriostatic agents inhibit growth; bactericidal agents kill bacteria", "Bacteriostatic agents always work faster", "Bactericidal agents only affect viruses", "They are the same"], 0, "Bacteriostatic drugs inhibit multiplication, relying partly on host defences, whereas bactericidal drugs kill bacteria; the distinction can depend on concentration and organism."],
    [I, "Pharmacology", "Drug half-life is related to the elimination rate constant k by…", ["t½ = 0.693 / k", "t½ = k / 0.693", "t½ = k × Vd", "t½ = CL / k"], 0, "For first-order elimination, t½ = ln2 / k, approximately 0.693 / k."],
    [I, "Pharmaceutics", "Which parameter is measured by the dissolution test of a solid oral dosage form?", ["Rate and extent of drug dissolving in a defined medium", "Tablet colour", "Particle charge", "Shelf life directly"], 0, "Dissolution testing measures the amount of drug dissolved over time under standardised conditions."],
    [I, "Pharmacognosy", "Which alkaloid-containing plant is the source of the antimalarial quinine?", ["Cinchona", "Digitalis", "Papaver somniferum", "Rauvolfia"], 0, "Quinine is obtained from the bark of Cinchona species."],

    /* ---------- ADVANCED ---------- */
    [A, "Pharmacokinetics", "In an oral one-compartment model, Tmax is given by…", ["ln(ka/k) / (ka − k)", "ln2 / k", "1 / ka", "(ka − k) / ln(ka/k)"], 0, "Setting dC/dt = 0 in the Bateman function gives Tmax = ln(ka/k)/(ka − k)."],
    [A, "Pharmacokinetics", "‘Flip-flop’ kinetics in an oral model occurs when…", ["ka is much smaller than k, so the terminal slope reflects absorption", "k is zero", "F is greater than one", "Vd is very small"], 0, "When ka < k, the slower process (absorption) determines the terminal phase, so the apparent terminal half-life reflects absorption, not elimination."],
    [A, "Pharmacokinetics", "Doubling the dose in a linear one-compartment model changes Cmax and AUC by what factor?", ["Both double", "Only Cmax doubles", "Only AUC doubles", "Neither changes"], 0, "Under linear kinetics, Cmax and AUC are proportional to dose (with F, CL and Vd constant)."],
    [A, "Pharmacokinetics", "If clearance is halved and Vd is unchanged, the half-life…", ["Doubles", "Halves", "Is unchanged", "Becomes zero"], 0, "t½ = 0.693·Vd / CL, so halving CL doubles t½ if Vd is constant."],
    [A, "Pharmaceutics", "Why is a curve fit to the Korsmeyer–Peppas model, by itself, insufficient to conclude the release mechanism?", ["Different mechanisms and system properties can give similar curves and n values", "The model has no equation", "Release is always zero-order", "n cannot be calculated"], 0, "Particle-size distribution, swelling, burst release and other factors can produce similar fits, so mechanism needs supporting evidence."],
    [A, "Pharmaceutics", "Which is a genuine limitation of the Higuchi model when applied to swelling or eroding polymer particles?", ["It assumes a non-swelling, non-eroding matrix with diffusion control", "It uses the wrong unit of time", "It requires zero drug", "It applies only to gases"], 0, "The Higuchi derivation assumes diffusion through an unchanging matrix, so swelling or erosion violates its assumptions."],
    [A, "Pharmaceutics", "In chitosan ionic gelation, raising the pH toward about 6.5 tends to…", ["Reduce protonation of amino groups and charge available for crosslinking", "Increase amino group protonation", "Convert chitosan to chitin", "Have no effect on solubility"], 0, "Deprotonation of amino groups near the pKa reduces positive charge, lowering solubility and electrostatic crosslinking capacity."],
    [A, "Pharmaceutics", "Which statement about degree of deacetylation (DD) is most accurate?", ["It is the fraction of glucosamine units, which influences charge density", "It is the molecular weight", "It is the particle size", "It is the drug loading"], 0, "DD describes the proportion of deacetylated (glucosamine) units. It affects charge density and solubility but is entangled with molecular weight."],
    [A, "Pharmaceutics", "A DLS measurement reports a low PDI. What is the most cautious conclusion?", ["The size distribution appears narrow by that method", "The product is safe", "Drug loading is high", "Release will be zero-order"], 0, "PDI speaks only to size-distribution breadth by that method; it does not establish safety, loading or release behaviour."],
    [A, "Pharmacovigilance", "A PRR of 3.1 with χ² of 6 and 5 cases in a spontaneous-report database most appropriately means…", ["The pair meets a screening rule and warrants further evaluation, not proof of causation", "The drug causes the event", "The event is common in the population", "The drug is unsafe and should be withdrawn"], 0, "Disproportionality flags hypotheses. Reporting biases and confounding mean a signal is not proof of causation."],
    [A, "Pharmacovigilance", "Why can disproportionality analysis flag a drug–event pair without any causal relationship?", ["Confounding by indication and reporting biases can inflate reporting", "PRR cannot exceed 1", "Databases contain only causal reports", "Chi-square proves causation"], 0, "The underlying disease, publicity, drug age and reporting behaviour can all create disproportionate reporting."],
    [A, "Pharmacovigilance", "In a Naranjo assessment, which answer to ‘Are there alternative causes that could on their own have caused the reaction?’ reduces the score?", ["Yes", "No", "Do not know only", "None of these"], 0, "A ‘Yes’ answer scores −1 for that question, while ‘No’ scores +2, reflecting reduced or increased likelihood of a drug cause."],
    [A, "Pharmacovigilance", "The odds-ratio-based measure used in signal detection is called…", ["Reporting Odds Ratio (ROR)", "Relative Risk Reduction", "Number Needed to Harm", "Hazard Ratio"], 0, "ROR = (a/b)/(c/d) = ad/bc, using the odds of the event among drug reports compared with other reports."],
    [A, "Analysis", "In HPLC, resolution (Rs) between two peaks improves when…", ["Selectivity, efficiency or retention is improved", "Peaks overlap more", "The column is shortened without other changes", "Detection wavelength is randomised"], 0, "Rs depends on efficiency (N), selectivity (α) and retention (k); improving any of these can improve separation."],
    [A, "Biostatistics", "A 95% confidence interval for an odds ratio that spans 1 indicates…", ["No statistically significant difference at the 5% level", "A very large effect", "The study is biased", "A p-value of exactly 0.95"], 0, "An interval containing 1 is consistent with no association, at the corresponding significance level."],
    [A, "Biopharmaceutics", "According to the Biopharmaceutics Classification System, a Class II drug has…", ["Low solubility and high permeability", "High solubility and high permeability", "Low solubility and low permeability", "High solubility and low permeability"], 0, "BCS Class II: low solubility, high permeability; dissolution is often rate-limiting for absorption."],
    [A, "Regulatory", "The primary purpose of process validation in pharmaceutical manufacturing is to…", ["Provide documented evidence that a process consistently produces product meeting specifications", "Reduce all costs", "Shorten patent life", "Replace quality control testing entirely"], 0, "Validation documents that a process, operated within defined parameters, consistently yields product of the required quality."],
    [A, "Microbiology", "Which mechanism is a common route by which bacteria acquire resistance to β-lactam antibiotics?", ["Production of β-lactamase enzymes", "Increased sensitivity of ribosomes", "Loss of all cell wall", "Reduced DNA content"], 0, "β-lactamases hydrolyse the β-lactam ring, inactivating the antibiotic; altered penicillin-binding proteins and efflux are other mechanisms."],
    [A, "Pharmaceutics", "Which change is most likely to increase the encapsulation efficiency reported by the indirect method, without changing actual drug entrapment?", ["Assay error underestimating free drug in the supernatant", "Using a fresh reference standard", "Measuring in triplicate", "Correct calibration"], 0, "Because the indirect method infers encapsulation by difference, underestimating free drug artificially raises the calculated EE%."],
    [A, "Pharmacokinetics", "Which is a valid limitation of a one-compartment model?", ["It treats distribution as instantaneous and may not fit multi-phase declines", "It cannot compute half-life", "It ignores dose", "It applies only to IV doses"], 0, "Many drugs show distributive phases that require two or more compartments."],

    /* ---------- RESEARCH ---------- */
    [R, "Pharmaceutics", "A paper reports a Korsmeyer–Peppas n of 0.45 for chitosan nanoparticles and concludes ‘Fickian diffusion.’ What is the most appropriate critical comment?", ["n cut-offs assume monodisperse spheres and the first ~60% of release; other factors can yield similar n, so the conclusion needs further support", "n = 0.45 proves diffusion", "n cannot be less than 0.5", "The equation is invalid for nanoparticles"], 0, "Mechanistic claims from n alone are weak, especially with polydisperse, swelling particles or burst effects."],
    [R, "Pharmaceutics", "A study of chitosan nanoparticles reports high EE% by the indirect method but no separate measure of particle-associated drug. What is the main concern?", ["Drug loss or degradation may be counted as encapsulated", "EE% cannot be measured", "Chitosan is insoluble", "The particle is too small"], 0, "The indirect method assumes any missing drug is in the particles; degradation or adsorption to labware would inflate EE%."],
    [R, "Pharmaceutics", "Two chitosan nanoparticle papers use different chitosan grades yet report opposite trends of size versus chitosan concentration. Which explanation is most reasonable?", ["Grade differences such as molecular weight and DD, and other conditions, can change the trend", "One paper must be fraudulent", "Concentration never affects size", "DLS is invalid"], 0, "Chitosan is a family of materials; results are grade- and condition-dependent, so trends are not universal."],
    [R, "Pharmaceutics", "Which is the most appropriate way to strengthen a claim that a nanoparticle’s drug is ‘molecularly dispersed’ based on XRD?", ["Combine with other techniques such as DSC and consider drug loading level", "State that absent peaks prove molecular dispersion", "Use a single XRD scan", "Ignore drug loading"], 0, "Low drug content can hide diffraction peaks; supporting evidence from complementary methods is needed."],
    [R, "Pharmacokinetics", "A pharmacokinetic simulation with fixed parameters produces a clean curve. What is the most important caveat when using it to reason about patients?", ["Parameters, variability and non-linearity in real patients are not represented", "The curve must be wrong", "Simulations cannot compute AUC", "Vd is negative"], 0, "A deterministic model with fixed parameters ignores between- and within-subject variability and possible non-linear kinetics."],
    [R, "Pharmacovigilance", "A signal is flagged for a drug used mainly in patients with a severe disease that itself causes the event. Which issue is most likely?", ["Confounding by indication", "Publication bias only", "Selection of the wrong chi-square test", "Placebo effect"], 0, "The underlying illness may produce the event and correlate with drug use, creating a non-causal disproportionality."],
    [R, "Pharmacovigilance", "Why should reporting rates in spontaneous databases generally not be interpreted as incidence?", ["Under-reporting is variable and no denominator of exposed patients is available", "They are always exact", "Only serious cases exist", "Reports are random"], 0, "Reporting is incomplete and influenced by many factors, and the number of exposed patients is unknown, so incidence cannot be derived."],
    [R, "AI in pharmacy", "A vendor claims an AI tool ‘never misses’ falsified tablets. What is the most appropriate response?", ["Request validation data on sensitivity, specificity and performance on unseen falsifications, and retain confirmatory testing", "Accept the claim", "Disable all testing", "Assume it is correct on all products"], 0, "No detection method is perfect; claims need validated performance data, and screening results require confirmation."],
    [R, "AI in pharmacy", "A model trained on data from one hospital performs well internally. What is the key concern before deploying it at another site?", ["Generalisability across populations, equipment and workflows requires external validation", "Nothing, as performance always transfers", "The model must be larger", "Accuracy is meaningless"], 0, "Differences in patients, data recording and practices can degrade performance, so external validation is needed."],
    [R, "AI in pharmacy", "Which statement about using a language model for literature review is most defensible?", ["It can assist with drafting and searching, but citations and claims must be verified against original sources", "It replaces reading the papers", "It never invents references", "It is always up to date"], 0, "Language models can produce plausible but incorrect statements and references, so verification is essential."],
    [R, "Biostatistics", "In a disproportionality analysis, adding many reports of an unrelated event for all drugs would most directly change which quantity?", ["The counts in b and d, and hence the comparison proportions", "The drug’s half-life", "The dose", "Vd"], 0, "The cell counts and thus the calculated proportions and odds change with the reporting background, illustrating sensitivity to database composition."],
    [R, "Biopharmaceutics", "A nanocarrier increases in-vitro cell uptake of a drug. What limits the inference that it will improve clinical outcome?", ["In-vitro uptake does not account for in-vivo barriers, distribution, toxicity and efficacy endpoints", "In-vitro data are always wrong", "Cells cannot take up particles", "Uptake has no relation to delivery"], 0, "Translation from cell culture to patients depends on many additional factors and requires in-vivo and clinical evidence."],
    [R, "Pharmaceutics", "Why can a positive zeta potential of a chitosan nanoparticle suspension measured in water not simply be assumed in physiological fluid?", ["pH, ionic strength and adsorbed proteins can alter surface charge and stability", "Zeta potential never changes", "Physiological fluid has no ions", "Chitosan becomes anionic"], 0, "Zeta potential is medium-dependent, and in biological fluids salts and proteins can screen or alter charge."],
    [R, "Regulatory", "Which factor most limits extrapolating a preclinical chitosan-nanoparticle result to a marketed product?", ["Scale-up, sterility, batch consistency, safety and regulatory requirements remain to be shown", "Chitosan is always banned", "Preclinical data are irrelevant", "Nanoparticles cannot be manufactured"], 0, "Translation requires demonstrating quality, safety and efficacy under regulatory standards, well beyond laboratory-scale results."],
    [R, "Pharmacokinetics", "When comparing two formulations, why is Cmax alone an incomplete descriptor of performance?", ["Exposure over time (AUC), Tmax and variability also matter", "Cmax is always identical", "AUC has no meaning", "Half-life is negative"], 0, "Formulation comparisons typically consider Cmax, Tmax and AUC together, with variability."]
  ];
  return raw.map(function (r, i) {
    return { id: "q" + (i + 1), level: r[0], domain: r[1], q: r[2], opts: r[3], a: r[4], e: r[5] };
  });
})();
